apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-users
  namespace: hotel-reservas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-users
  template:
    metadata:
      labels:
        app: postgres-users
    spec:
      containers:
      - name: postgres-users
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: users_db
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-users
  namespace: hotel-reservas
spec:
  selector:
    app: postgres-users
  ports:
  - port: 5432
